//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _32SA2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public string QuestionField1 { get; set; }
        public string QuestionField2 { get; set; }
        public string Duration { get; set; }
        public string DateTime { get; set; }
        public string UserID { get; set; }
        public string AspNetUserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Service Service { get; set; }
        public virtual PublicEvent PublicEvent { get; set; }
    }
}
