//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _32SA2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Id { get; set; }
        public string ServiceTitle { get; set; }
        public string Type { get; set; }
        public string ConsultantID { get; set; }
        public string TargetGroup { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Consultant Consultant { get; set; }
    }
}
